# configurations needed for project or framework
# define application defined or framework configuration details
# stores key-value pair


# centralized configuration: all critical settings in one place for easy management
# ease of maintenance: avoid hardcoding in the codebase; update settings without modifying code
# reuasability: same config file can be reused across multiple test cases or modules
# flexibility: quickly switch between environments (QA, prod...) by modifying a single file

##Application URL
url_old = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
url=http://localhost:82/orangehrm/orangehrm-5.8.1/web/index.php/auth/login
#Browser
browser = chrome

#Credentials
username = minousca
password = Minousca123@

#Implicit Wait (in seconds)
implicitWait = 5

#ExplicitWait (in seconds)
explicitWait = 5